apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: color-app-rs
  namespace: color-fe
  labels:
    infra: frontend
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        infra: frontend
        app: employees
    spec:
      containers:
      - name: webapp
        image: 954333580089.dkr.ecr.us-east-1.amazonaws.com/clo835-a1-webapp:latest
        imagePullPolicy: Always
        ports:
        - name: web8080
          containerPort: 8080
          protocol: TCP
        env:
        - name: DBHOST
          value: "mysql-db-rs.color-be"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-db-cred
              key: password
        - name: APP_COLOR
          value: "blue"
      imagePullSecrets:
      - name: ecr-cred