apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-db-rs
  namespace: color-be
  labels:
    infra: backend
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        infra: backend
        app: mysql
    spec:
      containers:
      - name: mysql-db
        image: 954333580089.dkr.ecr.us-east-1.amazonaws.com/clo835-a1-mysqldb:latest
        imagePullPolicy: Always
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-cred
              key: password
      imagePullSecrets:
      - name: regcred