apiVersion: v1
kind: Service
metadata:
  name: color-app-svc
  namespace: color-fe
  labels:
    infra: frontend
    app: employees
spec:
  type: NodePort
  selector:
      app: employees
  ports:
  - name: ext30000
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30000